### PR TITLE
Orc removal changes required to make postgres mostly work

### PR DESCRIPTION
**Pull request by anarazel**

### CODE REVIEW

**Comment by lhames** [comment]
Hi Andres,

The methods for adding MaterializationUnits should take either a JITDylib or a ResourceTracker but not both, since the ResourceTracker implies the JITDylib.

Would you like to make the changes? Otherwise I'm happy to do so.

**Comment by anarazel** [comment]
> The methods for adding MaterializationUnits should take either a JITDylib or a ResourceTracker but not both, since the ResourceTracker implies the JITDylib.

Are you thinking of exposing this on the the C API level, or only below? Should there be two functions? Or should usage of ResourceTracker be forced?

> Would you like to make the changes? Otherwise I'm happy to do so.

Whatever is most convenient for you.

**Comment by lhames** [comment]
> Are you thinking of exposing this on the the C API level, or only below? Should there be two functions? Or should usage of ResourceTracker be forced?

I was thinking I'd mirror the C++ API and provide two versions: One adding to the JITDylib on the default tracker, one taking a custom tracker.
 
> > Would you like to make the changes? Otherwise I'm happy to do so.
> 
> Whatever is most convenient for you.

Ok -- I'll update it tomorrow morning.

**Comment by lhames** [comment]
No luck updating this yet, sorry. Hopefully over the weekend or early next week.

**Comment by lhames** [comment]
This has been incorporated into the branch manually.

**Pull request closed without merging**
